# Enable external TCP listener
listener 1883
allow_anonymous true
max_packet_size 1600000
max_queued_messages 128
retain_available false
persistence true
persistence_location /mosquitto/data/

# Logging (for docker logs or local log files)
log_dest stdout
