listener_topic: "captain-compose/commands"
publisher_topic: "captain-compose/events"

mqtt:
  broker_url: "tcp://localhost:1883"
  client_id: "captain-compose"
  username: ""        # optional
  password: ""        # optional

  tls: # optional
    enable: false
    ca_cert_path: ""
    client_cert_path: ""
    client_key_path: ""
    insecure_skip_verify: false # only for development/testing

log:
  level: "info"        # debug, info, warn, error
  format: "text"       # text or json
  file_path: "./captain-compose.log" # optional log file
