name: Build and Release Binaries

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build for Linux
        run: GOOS=linux GOARCH=amd64 go build -o captain-compose-mqtt-linux ./cmd/captain-compose-mqtt

      - name: Build for macOS
        run: GOOS=darwin GOARCH=amd64 go build -o captain-compose-mqtt-darwin ./cmd/captain-compose-mqtt

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -o captain-compose-mqtt.exe ./cmd/captain-compose-mqtt

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            captain-compose-mqtt-linux
            captain-compose-mqtt-darwin
            captain-compose-mqtt.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
